In [1]:
import numpy as np

In [2]:
data_int = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [3]:
#DC_D1_W5_.9 Find missing values - Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.
data_int

array([[45,  8, 69, 91, 38],
       [47, 16, 31, 45, 19],
       [47, 30, 30, 14, 21],
       [83, 68, 63, 67, 23],
       [51, 12, 50, 61, 48]])

In [4]:
# generate 5 random indices 

In [5]:
data_int.shape

(5, 5)

In [6]:
random_idx = np.random.choice(data_int.size, 5)

In [7]:
random_idx

array([ 0,  8,  8, 21,  2])

In [8]:
#change to float since nan doesn't accept int
data_float = data_int.astype('float16')

In [9]:
data_float

array([[45.,  8., 69., 91., 38.],
       [47., 16., 31., 45., 19.],
       [47., 30., 30., 14., 21.],
       [83., 68., 63., 67., 23.],
       [51., 12., 50., 61., 48.]], dtype=float16)

In [11]:
data_float = data_float.reshape(25,)

In [12]:
data_float

array([45.,  8., 69., 91., 38., 47., 16., 31., 45., 19., 47., 30., 30.,
       14., 21., 83., 68., 63., 67., 23., 51., 12., 50., 61., 48.],
      dtype=float16)

In [14]:
data_float[random_idx] = np.nan

In [15]:
data_float

array([nan,  8., nan, 91., 38., 47., 16., 31., nan, 19., 47., 30., 30.,
       14., 21., 83., 68., 63., 67., 23., 51., nan, 50., 61., 48.],
      dtype=float16)

In [16]:
data_float2 = data_float.reshape(5,5)

In [17]:
data_float2

array([[nan,  8., nan, 91., 38.],
       [47., 16., 31., nan, 19.],
       [47., 30., 30., 14., 21.],
       [83., 68., 63., 67., 23.],
       [51., nan, 50., 61., 48.]], dtype=float16)

In [18]:

#True/False representation of the array based on condition
np.isnan(data_float2)

array([[ True, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [21]:
np.argwhere(np.isnan(data_float2))

array([[0, 0],
       [0, 2],
       [1, 3],
       [4, 1]])

In [23]:
#DC_D1_W5_.10 Replace the missing values in the data matrix with the mean of the matrix (ignoring the missing values while computing the mean

data_float2

array([[nan,  8., nan, 91., 38.],
       [47., 16., 31., nan, 19.],
       [47., 30., 30., 14., 21.],
       [83., 68., 63., 67., 23.],
       [51., nan, 50., 61., 48.]], dtype=float16)

In [28]:
#nanmean skips the nan values to calculate the mean of the array
matrix_mean = np.nanmean(data_float2)

In [29]:
matrix_mean

43.16

In [30]:
nan_idx = np.isnan(data_float2)

In [31]:
nan_idx

array([[ True, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [34]:
data_float2[nan_idx] = matrix_mean

In [35]:
data_float2

array([[43.16,  8.  , 43.16, 91.  , 38.  ],
       [47.  , 16.  , 31.  , 43.16, 19.  ],
       [47.  , 30.  , 30.  , 14.  , 21.  ],
       [83.  , 68.  , 63.  , 67.  , 23.  ],
       [51.  , 43.16, 50.  , 61.  , 48.  ]], dtype=float16)