In [3]:
import numpy as np

In [17]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [18]:
data

array([[31, 78, 37, 80, 91],
       [63, 11, 57, 13, 29],
       [26, 35, 30, 93, 59],
       [13, 87, 48, 21, 38],
       [50, 31, 67, 23, 39]])

In [19]:
#1 Swap the second and fourth rows of the data matrix
data[1], data[3] = data[3].copy(), data[1].copy()

In [20]:
data

array([[31, 78, 37, 80, 91],
       [13, 87, 48, 21, 38],
       [26, 35, 30, 93, 59],
       [63, 11, 57, 13, 29],
       [50, 31, 67, 23, 39]])

In [21]:
#2 Normalize all the elements in the data matrix such that they are scaled to range between 0 and 1.
min_val = data.min()

In [22]:
min_val

11

In [23]:
max_val = data.max()

In [25]:
max_val

93

In [26]:
normalize = (data - min_val) / (max_val - min_val)

In [27]:
normalize

array([[0.24390244, 0.81707317, 0.31707317, 0.84146341, 0.97560976],
       [0.02439024, 0.92682927, 0.45121951, 0.12195122, 0.32926829],
       [0.18292683, 0.29268293, 0.23170732, 1.        , 0.58536585],
       [0.63414634, 0.        , 0.56097561, 0.02439024, 0.2195122 ],
       [0.47560976, 0.24390244, 0.68292683, 0.14634146, 0.34146341]])

In [28]:
#3 Standardize the data matrix using Z-score normalization. That is, all the elements should be scaled to have a mean* of 0 and a standard deviation of 1.
mean_val = data.mean()

In [29]:
mean_val

46.0

In [30]:
std_val = data.std()

In [31]:
std_val

24.820958885586997

In [32]:
standardized = (data - mean_val) / std_val

In [33]:
standardized

array([[-0.60432798,  1.28923303, -0.36259679,  1.36981009,  1.81298395],
       [-1.32952156,  1.65182982,  0.08057706, -1.0072133 , -0.32230826],
       [-0.80577064, -0.44317385, -0.64461651,  1.89356101,  0.52375092],
       [ 0.68490505, -1.41009863,  0.44317385, -1.32952156, -0.68490505],
       [ 0.16115413, -0.60432798,  0.84605918, -0.92663624, -0.28201973]])

In [34]:
#4  Reshape the data matrix into a vector (Hint: use np.ravel) and split this array into five equal-sized sub-arrays.
vector = np.ravel(data)

In [35]:
sub_arrays = np.array_split(vector, 5)

In [36]:
sub_arrays

[array([31, 78, 37, 80, 91]),
 array([13, 87, 48, 21, 38]),
 array([26, 35, 30, 93, 59]),
 array([63, 11, 57, 13, 29]),
 array([50, 31, 67, 23, 39])]

In [37]:
vector

array([31, 78, 37, 80, 91, 13, 87, 48, 21, 38, 26, 35, 30, 93, 59, 63, 11,
       57, 13, 29, 50, 31, 67, 23, 39])

In [38]:
#5 Create two vectors of size 5 with any values. Compute the dot product of the two vectors
vector1 = np.array([3, 5, 6, 7, 8])

In [39]:
vector2 = np.array([2, 4, 6, 8, 10])

In [40]:
dot_product = np.dot(vector1, vector2)

In [41]:
dot_product

198

In [42]:
#6 create another 3x3 matrix with any values (let’s call it data2). Perform matrix multiplication (dot product of data (first 3x3 part) and data2).
data3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


In [45]:
data4 = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

In [46]:
result = np.dot(data3, data4)

In [47]:
result

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [48]:
#7 Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.
identity_matrix = np.eye(3)

In [49]:
scaled = 2 * identity_matrix

In [52]:
inverse_matrix = np.linalg.inv(scaled)

In [53]:
inverse_matrix

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

In [54]:
#8 For the first 3x3 part of the data matrix, compute the eigenvalues and eigenvectors
data_3x3 = data[:3, :3]


In [55]:
eigenvalues, eigenvectors = np.linalg.eig(data_3x3)

In [57]:
eigenvalues

array([129.83503947 +0.j        ,   9.08248027+11.83470257j,
         9.08248027-11.83470257j])

In [58]:
eigenvectors

array([[ 0.65562172+0.j        , -0.01717073+0.53274065j,
        -0.01717073-0.53274065j],
       [ 0.64284927+0.j        , -0.41753258-0.15230211j,
        -0.41753258+0.15230211j],
       [ 0.39611232+0.j        ,  0.71997443+0.j        ,
         0.71997443-0.j        ]])

In [59]:
#9 Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.
nan_indices = np.random.choice(data.size, 5, replace=False)

In [60]:
nan_indices

array([ 7,  2,  8, 24, 10])

In [62]:
data.ravel()[nan_indices] = np.nan

ValueError: cannot convert float NaN to integer

In [ ]:
# Encountered ValueError and couldn't proceed with the other parts of this exercise:
#Traceback (most recent call last)
#Cell In[62], line 1
#----> 1 data.ravel()[nan_indices] = np.nan