In [1]:
import numpy as np

In [4]:
#2.Create a vector* of zeros with size 10 using np.zeros(). [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

array_zero = np.zeros(10)

In [6]:
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#3 Compute the memory size* of any array. 
array_zero.itemsize

8

In [8]:
memory_size = array_zero.size * array_zero.itemsize

In [9]:
memory_size

80

In [11]:
#5 Create a vector with values ranging from 10 to 49 using np.arange()
my_vector = np.arange(10, 50)

In [12]:
my_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
#6 Reverse a vector so the first element becomes last
my_vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [14]:
#7 create a 3x3 matrix* with values ranging from 0 to 8
my_array = np.arange(0,9)

In [15]:
my_matrix = my_array.reshape(3,3)

In [16]:
my_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#8 Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().

array = np.array([1,2,0,0,4,0])

In [18]:
np.nonzero(array)

(array([0, 1, 4]),)

In [19]:
#9 Create a 3x3 identity matrix* using np.eye().
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#10 Create a 5x5 matrix with row values ranging from 0 to 4. The output should be a matrix where each row is [0, 1, 2, 3, 4].
my_array_rows = np.arange(5)

In [22]:
matrix_rows = np.tile(my_array_rows, (5, 1))

In [23]:
matrix_rows

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [24]:
#11 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
lin_array = np.linspace(0, 1, 10 )

In [25]:
lin_array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [28]:
lin_array2 = np.linspace(0, 1, 12 )[1:-1]

In [29]:
lin_array2

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [32]:
#12 Create a random vector of size 10 and sort it
random_vector = np.random.randint(10 , 30 , 10)

In [33]:
random_vector

array([23, 19, 25, 21, 15, 13, 13, 28, 16, 12])

In [34]:
sorted_vector = np.sort(random_vector)

In [35]:
sorted_vector

array([12, 13, 13, 15, 16, 19, 21, 23, 25, 28])

In [42]:
#13 Print the minimum and maximum representable value for each numpy scalar type* (int8, int32, int64, float32, float64). Use np.iinfo and np.finfo.
int_types = [np.int8, np.int32, np.int64]
for dtype in int_types:
    info = np.iinfo(dtype)
    print(f"for {dtype} Min is {info.min}, Max is {info.max}")


for <class 'numpy.int8'> Min is -128, Max is 127
for <class 'numpy.int32'> Min is -2147483648, Max is 2147483647
for <class 'numpy.int64'> Min is -9223372036854775808, Max is 9223372036854775807


In [44]:
float_types = [np.float32, np.float64]
for dtype in float_types:
    info = np.finfo(dtype)
    print(f"for {dtype} Min is {info.min}, Max is {info.max}")

for <class 'numpy.float32'> Min is -3.4028234663852886e+38, Max is 3.4028234663852886e+38
for <class 'numpy.float64'> Min is -1.7976931348623157e+308, Max is 1.7976931348623157e+308


In [45]:
#14 How to convert a float (32 bits) array into an integer (32 bits) in place?
float_array2 = np.array([1.2, 2.3, 3.4, 5.6, 7.8], dtype=np.float32)

In [48]:
float_array3 = float_array2.astype(np.int32)

In [49]:
float_array3

array([1, 2, 3, 5, 7], dtype=int32)

In [50]:
#15 Subtract the mean of each row of a matrix. 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [51]:
row_means = np.mean(matrix, axis=1, keepdims=True)


In [53]:
row_means

array([[2.],
       [5.],
       [8.]])

In [54]:
new_matrix = matrix - row_means

In [55]:
new_matrix

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [63]:
#16 How to sort an array by the nth column? Use np.argsort.
array2d = np.array([[4, 8, 3],[6, 3, 1],[9, 8, 4], [7, 9, 3]])

In [64]:
n = 1
array2d_sort = np.argsort(array2d[:, n]) 

In [67]:
sorted_2d = array2d[array2d_sort]

In [68]:
sorted_2d

array([[6, 3, 1],
       [4, 8, 3],
       [9, 8, 4],
       [7, 9, 3]])

In [71]:
#17 How to swap two rows of an array? You can do this using array indexing.
array2d[[0,1]] = array2d[[1, 0]]

In [72]:
array2d

array([[4, 8, 3],
       [6, 3, 1],
       [9, 8, 4],
       [7, 9, 3]])

In [73]:
#Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.

C = np.array([0, 2, 3, 0, 1, 0, 1])

In [74]:
A = np.repeat(np.arange(len(C)), C)

In [75]:
A 

array([1, 1, 2, 2, 2, 4, 6])