# Intro

In [1]:
import numpy as np #numerical python

In [2]:
1 + 2

3

# header

In [8]:
array = np.array([1,2,3,4,5])

In [9]:
array

array([1, 2, 3, 4, 5])

In [10]:
array2 = np.array([1,2,3,4,5])

In [11]:
array * array2

array([ 1,  4,  9, 16, 25])

# Array attributes

In [12]:
array.ndim #number of dimensions - how many lines of numbers (x (axes - columns) - one dim, y (axes - rows) - 2d)

1

In [15]:
two_dim_array = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]) #amount of [] says how many dimensions

In [16]:
two_dim_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [17]:
two_dim_array.ndim

2

In [18]:
#shape - amount of rows/columns etc.
array.shape

(5,)

In [19]:
two_dim_array.shape

(3, 5)

In [20]:
two_dim_array.size

15

In [21]:
#data type
two_dim_array.dtype

dtype('int64')

# Converting from one type to another

In [22]:
float_array = array.astype('float16')

In [23]:
float_array.dtype

dtype('float16')

In [24]:
float_array

array([1., 2., 3., 4., 5.], dtype=float16)

# Creating array

In [25]:
my_array = np.arange(1, 10)

In [26]:
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercise

In [30]:
array_new = np.arange(10, 21)

In [31]:
array_new

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
array_new.ndim

1

In [33]:
array_new.shape

(11,)

In [34]:
array_new.size

11

In [35]:
array_new.dtype

dtype('int64')

In [36]:
float_array_new = np.arange(10.0, 21.0)  #or make it (10, 21, dtype = 'float16')

In [37]:
float_array_new

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [38]:
float_array_new.dtype

dtype('float64')

In [39]:
int_array_new = float_array_new.astype('int64')

In [40]:
int_array_new.dtype

dtype('int64')

In [41]:
int_array_new * 2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

# INDEXING - one dimension

In [42]:
one_dim_array = np.arange(11)

In [43]:
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
one_dim_array[1] #second

1

In [45]:
one_dim_array[0] #first

0

In [46]:
one_dim_array[-1]

10

In [48]:
one_dim_array[1:5]

array([1, 2, 3, 4])

In [49]:
one_dim_array[2::2] #only devided by two

array([ 2,  4,  6,  8, 10])

# INDEXING - two dimension

In [50]:
two_dim_array = np.arange(10)

In [51]:
two_dim_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
two_dim_array.size

10

In [53]:
two_dim_array.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
two_dim_array = two_dim_array.reshape((5,2))

In [58]:
two_dim_array[1] #second row

array([2, 3])

In [59]:
two_dim_array[1:3] #index through rows

array([[2, 3],
       [4, 5]])

In [60]:
two_dim_array[1:3, 0] #index through rows + taking first 1ST item

array([2, 4])

In [61]:
two_dim_array[::-1] #reversing the array

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

### Exercise 2

In [64]:
my_int_array = np.arange(10, 21)

In [65]:
my_int_array[3]

13

In [66]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [69]:
my_2d_array[1][2]

6

In [72]:
my_1d_array = np.arange(10)

In [73]:
my_1d_array[2:6]

array([2, 3, 4, 5])

In [74]:
my_2d_new_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [79]:
my_2d_new_array[:2, 1:]

array([[2, 3],
       [5, 6]])

# Generation ARANGE

In [80]:
array = np.arange(1,100)

In [82]:
array_decimal = np.arange (0, 10, 0.1)

In [83]:
array_decimal

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [84]:
array_decimal.reshape(10, 10)

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

# Generation LINSPACE

In [87]:
lin_array = np.linspace(0, 5, 100) #create specific number of items at a specific range

In [88]:
lin_array

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# Generation RANDOM

In [93]:
np.random.randint(0, 10)

7

In [94]:
np.random.rand(2, 2) #create an array with a specific shape with random floats

array([[0.38906508, 0.95674719],
       [0.8425157 , 0.53344158]])

### Exercise 3

In [95]:
one_array = np.arange(20, 31)

In [96]:
one_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [97]:
even_array = np.arange(10, 21, 2)

In [98]:
even_array

array([10, 12, 14, 16, 18, 20])

In [99]:
my_lin_array = np.linspace(0, 1, 5)

In [100]:
my_lin_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [101]:
my_rand_array = np.random.rand(0, 1, 3) 

In [102]:
my_rand_array

array([], shape=(0, 1, 3), dtype=float64)

In [103]:
my_rand_array = np.random.rand(3) 

In [104]:
my_rand_array 

array([0.58995268, 0.93287913, 0.43833295])

In [105]:
my_random_array = np.random.randint(1, 10, 4)

In [106]:
my_random_array 

array([5, 3, 9, 2])

# MATRIX OPERATIONS

In [107]:
my_twodim_array = np.arange(0,25)

In [109]:
my_twodim_array = my_twodim_array.reshape(5,5)

In [110]:
my_twodim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# X - 0 columns
# Y - 1 rows

## The Mean

In [111]:
#(1,2,3,4,5) = (1+2+3+4+5)/5 = 3.0 ---> the mean! 
my_twodim_array.mean() #based on the whole matrix


12.0

In [112]:
my_twodim_array.mean(axis=1) #based on rows

array([ 2.,  7., 12., 17., 22.])

In [113]:
my_twodim_array.mean(axis=0) #based on columns

array([10., 11., 12., 13., 14.])

## Sorting

In [114]:
my_twodim_array.argsort() #produce the sorting order based on the rows

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [115]:
my_twodim_array.argsort(axis=0) #produce the sorting order based on the columns

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

## Swapping

In [118]:
my_twodim_array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [117]:
my_twodim_array[[0,1]] = my_twodim_array[[1, 0]]

In [119]:
my_twodim_array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# FUNCTIONS